apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    test: project-test
spec: 
  containers:
    - image: mahmoudelsayed481/myimageproject
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      name: myimageproject-container
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"    
