apiVersion: v1
kind: Service
metadata:
  name: port-service
  labels:
    test: project-test
spec: 
  type: NodePort
  selector:
    test: project-test
  ports:
    - port: 8011
      targetPort: 80
      nodePort: 30005
